name: C/C++ CI

on:
  push:
    branches: [ "master/Windows Unsafe DLL Loading" ]
  pull_request:
    branches: [ "master/Windows Unsafe DLL Loading" ]

jobs:

   build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
      - name: Build
        run: dotnet build
      - name: Run tests
        run: dotnet test

