name: C/C++ CI

on:
  push:
    branches: [ "master/Windows Unsafe DLL Loading" ]
  pull_request:
    branches: [ "master/Windows Unsafe DLL Loading" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
